//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrators
    {
        public int adminID { get; set; }

        [Required]
        [DisplayName("Admin Username")]
        public string admin_username { get; set; }

        [Required]
        [DisplayName("Admin Password")]
        public string admin_password { get; set; }

        [Required]
        [DisplayName("Admin Fullname")]
        public string admin_fullname { get; set; }
    }
}
