//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.AssignCourse = new HashSet<AssignCourse>();
            this.Topic = new HashSet<Topic>();
            this.Enroll = new HashSet<Enroll>();
            this.Events = new HashSet<Events>();
        }
    
        public int courseID { get; set; }

        [Required]
        [DisplayName("Course Name")]
        public string course_name { get; set; }

        [DisplayName("Course Image")]
        public string course_image { get; set; }

        [DisplayName("Description")]
        public string course_descriptions { get; set; }

        [DisplayName("Category")]
        public Nullable<int> categoryID { get; set; }

        [DisplayName("Course Materials")]
        public string course_materials { get; set; }

        [Required]
        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime startDate { get; set; }

        [Required]
        [DisplayName("End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime endDate { get; set; }

        [Required]
        [DisplayName("Course Duration")]
        public string course_duration { get; set; }

        [Required]
        [DisplayName("Number of student")]
        public int numStd { get; set; }

        [DisplayName("Status")]
        public string course_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignCourse> AssignCourse { get; set; }
        public virtual CourseCategories CourseCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
    }
}
