//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Request
    {
        public int requestID { get; set; }

        [Required]
        [DisplayName("Request Subject")]
        public string request_subject { get; set; }


        [DisplayName("Description")]
        public string request_descriptions { get; set; }


        [DisplayName("Answer")]
        public string request_answer { get; set; }
        public System.DateTime request_date { get; set; }

        [DisplayName("Status")]
        public string request_status { get; set; }
        public int trainerID { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
