//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Enroll = new HashSet<Enroll>();
        }
    
        public int traineeID { get; set; }

        [Required]
        [DisplayName("Username")]
        public string trainee_username { get; set; }

        [Required]
        [DisplayName("Password")]
        public string trainee_password { get; set; }

        [Required]
        [DisplayName("Fullname")]
        public string trainee_fullname { get; set; }


        [DisplayName("Age")]
        public Nullable<int> trainee_age { get; set; }


        [DisplayName("Date of birth")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> trainee_birthday { get; set; }


        [DisplayName("Education")]
        public string trainee_education { get; set; }

        [Required]
        [DisplayName("Email")]
        public string trainee_email { get; set; }

        [Required]
        [DisplayName("Phone")]
        public string trainee_phone { get; set; }


        [DisplayName("Experience")]
        public string trainee_experience_details { get; set; }

  
        [DisplayName("Department")]
        public string trainee_department { get; set; }

        [Required]
        [DisplayName("Address")]
        public string trainee_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enroll { get; set; }
    }
}
