//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainingStaff
    {
        public int staffID { get; set; }

        [Required]
        [DisplayName("Username")]
        public string staff_username { get; set; }

        [Required]
        [DisplayName("Password")]
        public string staff_password { get; set; }

        [Required]
        [DisplayName("Fullname")]
        public string staff_fullname { get; set; }

        [DisplayName("Address")]
        public string staff_address { get; set; }

        [DisplayName("Email")]
        public string staff_email { get; set; }
    }
}
